gobusgo_gobusgo_homepage:
    path:     /
    defaults: { _controller: GobusgoGobusgoBundle:Page:index }

gobusgo_gobusgo_catalog:
    path:     /catalog
    defaults: { _controller: GobusgoGobusgoBundle:Page:catalog }

gobusgo_gobusgo_autopark:
    path:     /autopark
    defaults: { _controller: GobusgoGobusgoBundle:Page:autopark }

gobusgo_gobusgo_about:
    path:     /about-us
    defaults: { _controller: GobusgoGobusgoBundle:Page:about }

gobusgo_gobusgo_feedback:
    path:     /feedback
    defaults: { _controller: GobusgoGobusgoBundle:Page:feedback }

gobusgo_gobusgo_deliveryRB:
    path:     /gruzoperevozki-po-belarusi
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryRB }

gobusgo_gobusgo_deliveryRB:
    path:     /gruzoperevozki-po-belarusi
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryRB }

gobusgo_gobusgo_deliveryMinsk:
    path:     /delivery-Minsk
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryMinsk }

gobusgo_gobusgo_deliveryMinskMoscow:
    path:     /delivery-Minsk-Moscow
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryMinskMoscow }

gobusgo_gobusgo_deliveryMoscowMinsk:
    path:     /delivery-Moscow-Minsk
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryMoscowMinsk }

gobusgo_gobusgo_contacts:
    path:     /contacts
    defaults: { _controller: GobusgoGobusgoBundle:Page:contacts }