gobusgo_gobusgo_homepage:
    path:     /
    defaults: { _controller: GobusgoGobusgoBundle:Page:index }

gobusgo_gobusgo_catalog:
    path:     /catalog
    defaults: { _controller: GobusgoGobusgoBundle:Page:catalog }

gobusgo_gobusgo_autopark:
    path:     /autopark
    defaults: { _controller: GobusgoGobusgoBundle:Page:autopark }

gobusgo_gobusgo_about:
    path:     /about-us
    defaults: { _controller: GobusgoGobusgoBundle:Page:about }

gobusgo_gobusgo_feedback:
    path:     /feedback
    defaults: { _controller: GobusgoGobusgoBundle:Page:feedback }

gobusgo_gobusgo_deliveryRB:
    path:     /gruzoperevozki-po-belarusi
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryRB }

gobusgo_gobusgo_deliveryMinsk:
    path:     /delivery-Minsk
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryMinsk }

gobusgo_gobusgo_deliveryMoscowMinsk:
    path:     /delivery-Moscow-Minsk
    defaults: { _controller: GobusgoGobusgoBundle:Page:deliveryMoscowMinsk }
    requirements:
        methods:  GET|POST

gobusgo_gobusgo_contacts:
    path:     /contacts
    defaults: { _controller: GobusgoGobusgoBundle:Page:contacts }

gobusgo_gobusgo_confirm:
    path:     /confirm
    defaults: { _controller: GobusgoGobusgoBundle:Page:confirm }


#    ------------------------------blog

gobusgo_gobusgo_blog:
    path:     /blog
    defaults: { _controller: GobusgoGobusgoBundle:Page:blog }
    requirements:
        methods:  GET|POST

gobusgo_gobusgo_blog_show:
    path:     /blog/{id}/{url}
    defaults: { _controller: GobusgoGobusgoBundle:Page:blogShow }
    requirements:
        methods:  GET|POST
        id: \d+

gobusgo_gobusgo_comment_create:
    path:  /comment/{blog_id}
    defaults: { _controller: GobusgoGobusgoBundle:Comment:create }
    requirements:
        methods:  POST
        blog_id: \d+


gobusgo_gobusgo_category:
    path:  /blog/category/{id}/{category}
    defaults: { _controller: GobusgoGobusgoBundle:Page:category,  }
    requirements:
        methods:  POST
        id: \d+
